[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom"]
    type = "git-repo"
    url = "https://gitlab.com/changyoungkwon/zsh-custom.git"
    clone.args=["--recursive"]
    exact = true
    stripComponents = 1
